# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0003_auto_20170304_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
