# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0004_auto_20170305_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
