# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elements', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
