# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('studentCode', models.IntegerField(blank=True)),
                ('mail', models.EmailField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('grade', models.CharField(choices=[('A', 'hola'), ('B', 'hola')], max_length=10)),
            ],
        ),
    ]
