# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_remove_student_studentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('8A', '8A'), ('8B', '8B'), ('8C', '8C'), ('8D', '8D'), ('9A', '9A'), ('9B', '9B'), ('9C', '9C'), ('9D', '9D'), ('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C')], max_length=10),
        ),
    ]
